<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Color;

class ColorSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $colors = [
            // Básicos
            'Rojo',
            'Azul',
            'Verde',
            'Amarillo',
            'Negro',
            'Blanco',
            'Rosa',
            'Fucsia',
            'Violeta',
            'Púrpura',
            'Lila',
            'Naranja',
            'Marrón',
            'Beige',
            'Gris',
            // Azules
            'Celeste',
            'Azul Marino',
            'Azul Rey',
            'Azul Claro',
            'Azul Acero',
            'Azul Petróleo',
            'Azul Cobalto',
            'Azul Eléctrico',
            'Azul Pizarra',
            'Azul Medianoche',
            'Azul Pavo Real',
            'Azul Hielo',
            'Azul Cielo',
            'Azul Cian',
            'Azul Zafiro',
            'Azul Pastel',
            'Azul Índigo',
            'Azul Persa',
            'Azul Turquí',
            'Azul Bebé',
            // Verdes
            'Turquesa',
            'Aqua',
            'Verde Lima',
            'Verde Oscuro',
            'Verde Oliva',
            'Menta',
            'Verde Agua',
            'Verde Esmeralda',
            'Verde Musgo',
            'Verde Bosque',
            'Verde Salvia',
            'Verde Pino',
            'Verde Jade',
            'Verde Manzana',
            'Verde Pistacho',
            'Verde Menta Pastel',
            'Verde Caqui',
            'Verde Cazador',
            'Verde Neon',
            'Verde Helecho',
            'Verde Pasto',
            'Verde Selva',
            'Verde Botella',
            'Verde Aquamarina',
            // Rojos y rosas
            'Rojo Oscuro',
            'Bordo',
            'Coral',
            'Salmón',
            'Melocotón',
            'Vino',
            'Granate',
            'Rojo Carmesí',
            'Rojo Rubí',
            'Rojo Escarlata',
            'Rojo Ladrillo',
            'Rojo Frambuesa',
            'Rojo Tomate',
            'Rojo Cereza',
            'Rosa Pastel',
            'Rosa Bebé',
            'Rosa Chicle',
            'Rosa Viejo',
            'Rosa Suave',
            'Rosa Intenso',
            'Rosa Pálido',
            'Rosa Flamenco',
            'Rosa Claro',
            'Rosa Fucsia Pastel',
            'Rosa Blush',
            'Rosa Coral',
            // Naranjas y amarillos
            'Naranja Quemado',
            'Naranja Calabaza',
            'Naranja Melocotón',
            'Naranja Mandarina',
            'Naranja Neon',
            'Naranja Durazno',
            'Durazno',
            'Mostaza',
            'Amarillo Limón',
            'Amarillo Pastel',
            'Amarillo Oro',
            'Amarillo Neon',
            'Amarillo Canario',
            'Amarillo Paja',
            'Amarillo Crema',
            'Amarillo Arena',
            'Amarillo Champán',
            // Marrones y neutros
            'Chocolate',
            'Caramelo',
            'Arena',
            'Crema',
            'Marfil',
            'Caqui',
            'Canela',
            'Café',
            'Café con Leche',
            'Tostado',
            'Siena',
            'Terracota',
            'Ocre',
            'Cuero',
            'Camello',
            'Avellana',
            'Nuez',
            'Cobre',
            'Tabaco',
            'Taupe',
            'Topo',
            'Lino',
            'Piedra',
            // Grises y negros
            'Gris Claro',
            'Gris Oscuro',
            'Carbón',
            'Gris Perla',
            'Gris Humo',
            'Gris Plata',
            'Gris Pizarra',
            'Gris Marengo',
            'Gris Frío',
            'Gris Cálido',
            'Gris Azulado',
            'Gris Verdoso',
            'Gris Grafito',
            'Gris Cemento',
            'Antracita',
            'Ebano',
            'Negro Azabache',
            'Negro Grafito',
            // Metálicos y especiales
            'Dorado',
            'Plateado',
            'Bronce',
            'Cobre Metálico',
            'Champán',
            'Oro Rosa',
            'Oro Viejo',
            'Plata Brillante',
            'Titanio',
            // Lilas, violetas y morados
            'Lavanda',
            'Magenta',
            'Cyan',
            'Índigo',
            'Lila Pastel',
            'Violeta Oscuro',
            'Violeta Claro',
            'Malva',
            'Orquídea',
            'Ciruela',
            'Berenjena',
            'Amatista',
            'Uva',
            'Morado Pastel',
            'Violeta Pastel',
            // Especiales y estampados
            'Multicolor',
            'Estampado',
            'Tie Dye',
            'Degradado',
            'Camuflaje',
            'Animal Print',
            'Lunares',
            'Rayas',
            'Cuadros',
            'Floreado',
            'Transparente',
        ];

        foreach ($colors as $color) {
            Color::create(['name' => $color]);
        }
    }
}